import type { Country, CountryCode } from "@/types";

export const countries: Record<CountryCode, Country> = {
  uae: {
    code: "uae",
    name: "UAE",
    flag: "🇦🇪",
    accentColor: "#0066CC",
    currency: "AED",
    exchangeName: "ADX / DFM",
    timezone: "Asia/Dubai",
  },
  ksa: {
    code: "ksa",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    accentColor: "#006B3F",
    currency: "SAR",
    exchangeName: "Tadawul",
    timezone: "Asia/Riyadh",
  },
  qatar: {
    code: "qatar",
    name: "Qatar",
    flag: "🇶🇦",
    accentColor: "#8A1538",
    currency: "QAR",
    exchangeName: "QSE",
    timezone: "Asia/Qatar",
  },
  kuwait: {
    code: "kuwait",
    name: "Kuwait",
    flag: "🇰🇼",
    accentColor: "#007A5E",
    currency: "KWD",
    exchangeName: "Boursa Kuwait",
    timezone: "Asia/Kuwait",
  },
  bahrain: {
    code: "bahrain",
    name: "Bahrain",
    flag: "🇧🇭",
    accentColor: "#CE1126",
    currency: "BHD",
    exchangeName: "Bahrain Bourse",
    timezone: "Asia/Bahrain",
  },
  oman: {
    code: "oman",
    name: "Oman",
    flag: "🇴🇲",
    accentColor: "#D12D1C",
    currency: "OMR",
    exchangeName: "MSM",
    timezone: "Asia/Muscat",
  },
  egypt: {
    code: "egypt",
    name: "Egypt",
    flag: "🇪🇬",
    accentColor: "#C89B3C",
    currency: "EGP",
    exchangeName: "EGX",
    timezone: "Africa/Cairo",
  },
  gcc_wide: {
    code: "gcc_wide",
    name: "GCC-wide",
    flag: "🌍",
    accentColor: "#8B5CF6",
    currency: "",
    exchangeName: "",
    timezone: "Asia/Dubai",
  },
  international: {
    code: "international",
    name: "International",
    flag: "🌐",
    accentColor: "#6B7280",
    currency: "",
    exchangeName: "",
    timezone: "UTC",
  },
};

export const gccCountryCodes: CountryCode[] = [
  "uae",
  "ksa",
  "qatar",
  "kuwait",
  "bahrain",
  "oman",
  "egypt",
];
